# Generated by Django 5.2.6 on 2025-10-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golls', '0002_student_teacher_alter_golls_lastname_course'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='golls',
            table='golls',
        ),
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
