# Generated by Django 5.2.6 on 2025-10-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golls', '0003_alter_course_table_alter_golls_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='golls.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golls.teacher')),
            ],
            options={
                'db_table': 'tests',
            },
        ),
    ]
