# Generated by Django 5.2.6 on 2025-10-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golls', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golls',
            name='lastName',
            field=models.CharField(max_length=200),
        ),
    ]
